version: '2'
services:
  cattle:
    build: ./
    image: clariah/cattle:latest
    restart: unless-stopped
    ports:
     - "8001:80"
    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
     - AUTH_TOKEN=xxx
